### PR TITLE
Cuda stubs symlink

### PR DESCRIPTION
**Pull request by rgarbage**
Requesting review from @civodul 

Maybe 's/Many/Some/' in the comment :)

### CODE REVIEW

**Comment by civodul** [comment]
Hey @rgarbage! Since this is all about accommodating some packages, how annoying would it be to just fix those packages?

7d4292bc2fdbe3b5a7f0e0e6dc1ffb37db55ff63 already added a `lib64 -> lib` symlink for old CUDA versions, so it would be consistent to add it here, but can we keep the `fix-stubs-path` phases so `lib` remains the preferred location?

**Comment by rgarbage** [comment]
@civodul it is not possible to add a `lib64 -> lib` symlink in the newer CUDA packages because the output contains both a `lib` and a `lib64` folder with different content (due to the `install-cupti` phase introduced in `cuda-11.0` IIRC).

Maybe the installation related phases have to be reworked?

**Comment by civodul** [comment]
Hello @rgarbage! Yeah, I get that the pragmatic approach is not to rewrite every package that uses CUDA, like those `fix-stub-paths` phases were doing.  All good!

**Comment by civodul** [comment]
Pushed as e09ba7b4fd0973107404400a0020493035590fd3, thanks!

**Pull request closed without merging**
